# Exported from Render on 2025-01-16T09:14:59Z
databases:
  - name: gallery_on_rails_psql
    databaseName: gallery_on_rails_production_ptrs
    user: developer
    plan: free
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "16"

services:
  - type: web
    name: Gallery-On-Rails
    runtime: ruby
    plan: free
    # buildCommand: "./bin/render-build.sh"
    # preDeployCommand: "bundle exec rails db:migrate" # preDeployCommand only available on paid instance types
    # startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gallery_on_rails_production_ptrs
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default